name: Run React Native Harness Android

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/harness-android.yml'
      - 'example/**'
      - 'packages/react-native-nitro-lunar-range-picker/android/**'
      - 'packages/react-native-nitro-lunar-range-picker/ios/**'
      - 'packages/react-native-nitro-lunar-range-picker/cpp/**'
      - 'packages/react-native-nitro-lunar-range-picker/src/**'
      - 'packages/react-native-nitro-lunar-range-picker/nitrogen/**'
      - 'packages/react-native-nitro-lunar-range-picker/*.podspec'
      - 'packages/react-native-nitro-lunar-range-picker/package.json'
      - 'bun.lock'
      - 'pnpm-lock.yaml'
      - 'package-lock.json'
      - 'yarn.lock'
      - 'packages/react-native-nitro-lunar-range-picker/react-native.config.js'
      - 'packages/react-native-nitro-lunar-range-picker/nitro.json'
  pull_request:
    paths:
      - '.github/workflows/harness-android.yml'
      - 'example/**'
      - 'packages/react-native-nitro-lunar-range-picker/android/**'
      - 'packages/react-native-nitro-lunar-range-picker/ios/**'
      - 'packages/react-native-nitro-lunar-range-picker/cpp/**'
      - 'packages/react-native-nitro-lunar-range-picker/src/**'
      - 'packages/react-native-nitro-lunar-range-picker/nitrogen/**'
      - 'packages/react-native-nitro-lunar-range-picker/*.podspec'
      - 'packages/react-native-nitro-lunar-range-picker/package.json'
      - 'bun.lock'
      - 'pnpm-lock.yaml'
      - 'package-lock.json'
      - 'yarn.lock'
      - 'packages/react-native-nitro-lunar-range-picker/react-native.config.js'
      - 'packages/react-native-nitro-lunar-range-picker/nitro.json'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Android Harness
    runs-on: ubuntu-latest
    env:
      AVD_DISK_SIZE: 1G
      AVD_HEAP_SIZE: 1G
      AVD_NAME: Pixel_7_API_36
      DEVICE_API_LEVEL: '36'
      DEVICE_ARCH: x86_64
      DEVICE_PROFILE: pixel_7
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'


      - name: Install dependencies
        run: npm install

      - name: Run codegen and build
        run: npm run codegen && npm run build

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Build Android app
        working-directory: example/android
        run: |
          chmod +x ./gradlew
          ./gradlew :app:assembleDebug --no-daemon --build-cache -PreactNativeArchitectures=${{ env.DEVICE_ARCH }}

      - name: Run React Native Harness
        uses: callstackincubator/react-native-harness@v1.4.1
        with:
          app: android/app/build/outputs/apk/debug/app-debug.apk
          runner: android
          projectRoot: example
          packageManager: npm

      - name: Stop Gradle
        if: always()
        working-directory: example/android
        run: |
          chmod +x ./gradlew
          ./gradlew --stop
